import { Navbar } from '@/components/ui/Navbar';
import MantineProviderCWrapper from '@/providers/mantineProvider';

import cn from '@/app/page.module.scss';

export const metadata = {
  title: 'ITWEBS-test',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MantineProviderCWrapper>
          <main className={cn.main}>
            <Navbar />
            <aside className={cn.aside}>{children}</aside>
          </main>
        </MantineProviderCWrapper>
      </body>
    </html>
  );
}
